### ISSUE TITLE
Amani-Zen: Missing subheadings on Resources page

### ISSUE THREAD

**Issue by dannyzoujx** [PeaceGeeksSociety/amani#1028]
Subheadings like "Featured Resources" and "All Resources" are missing on the dev site

Invision:
![resources_invision](https://cloud.githubusercontent.com/assets/15751109/11575302/23ea1c4e-99c5-11e5-8c9d-b3c7e3ab0234.png)

**Comment by dannyzoujx** [comment]
Just adding a note as this is for both Desktop and Mobile version
![resources_header_invision](https://cloud.githubusercontent.com/assets/15751109/11698601/42bd04fc-9e74-11e5-8378-3eb1b2f899ac.png)

**Comment by sheilaj** [comment]
I added a view for Featured Resources and a context to place it. I also added a Keyword filter, as per mock.

Theming is needed. Views overlap and existing theming is broken on the exposed filter form because I moved it to a block (otherwise it is displayed beside the All Resources view, which is now lower on the page, below the Featured Resources view).

**Comment by limage** [comment]
Done!

**Comment by akochlan** [comment]
Validated on dev env. Sub-headers have been added but they should be capitalized like 'FEATURED RESOURCES' according to mockup. Failed.

**Comment by akochlan** [comment]
Re-tested after updating dev. Passed.

**Comment by PeaceGeeksProjects** [comment]
Verified
