### ISSUE TITLE
Amani-Zen: Incorrect calendar widget on News & Events

### ISSUE THREAD

**Issue by dannyzoujx** [PeaceGeeksSociety/amani#1039]
There are some discrepancy between Invision and Frontify, but the correct design for widgets on News & Events should be Upcoming Events widget and a Calendar widget.

So it should have 2 widgets like on Invision but without the texture: https://projects.invisionapp.com/share/KB4R6KBD9#/screens/116357094
![news_events_widgets](https://cloud.githubusercontent.com/assets/15751109/11597028/b64447e2-9a6d-11e5-91d9-b02faf7aa1f8.png)

**Comment by PeaceGeeks** [comment]
I would also keep the upcoming events to the top 3

**Comment by bensinjin** [comment]
See http://dev.amani-zen-theme.peacegeeks.org/news-and-events.

**Comment by akochlan** [comment]
Validated on dev env. I am not sure what was the issue with calendar widget, no desc or screenshot. Looks good except no pagination on the bottom, see mockup. Failed.

**Comment by PeaceGeeksProjects** [comment]
Pagination appears OK now, HOWEVER backwards works fine, but forwards jumps by 2 month...

Moving back to ToDo

**Comment by erica-scott** [comment]
https://www.drupal.org/node/2375235
Based on this forum, figured out this is an issue with the date module and taking the +1 month jump "too literally", basically it jumps exactly 31 days, so if it tries to jump to a month that only has 30 days such as April, it jumps to May because it's jumping to May 1 technically.

Implementing the patch from the link (number 35) fixes the issue.

**Comment by PeaceGeeksProjects** [comment]
Verified on Dev & LYM
