### ISSUE TITLE
Taxonomy views should look like normal views

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/amani#1080]
Requested by Libya
e.g. http://dev.libya.peacegeeks.org/?q=resource-theme/our-impact
vs
http://dev.libya.peacegeeks.org/?q=resources

**Comment by erica-scott** [comment]
I made the appropriate back end changes so that the taxonomy pages for 'Resource Theme' and 'Resource Type' both link to the view that the resources page also links too. Now, going to http://dev.libya.peacegeeks.org/?q=taxonomy/term/238 or http://dev.libya.peacegeeks.org/?q=resource-theme/our-impact displays it as the view. 

I also had to apply a patch to the Taxonomy Display module as it was not possible to override the title of the view page to say 'Resources' without it. 

The only problem is that the CSS that styles the original resource view page does not apply to these views, so CSS will need to be added to make the pages look the same.

**Comment by limage** [comment]
Each taxonomy views should be added a wrapper class. Please refer to page: http://dev.libya.peacegeeks.org/resources.

**Comment by bensinjin** [comment]
@limage can you clarify? What needs to be done to the taxonomy views?

**Comment by limage** [comment]
@bensinjin Please wrap taxonomy resource list item(inluding image; content; links) into views-row, check the screen shot  here http://cl.ly/2L0r123h2f23 
Leftside is source code from http://dev.libya.peacegeeks.org/resource-theme/our-impact;  Rightside is source code from http://dev.libya.peacegeeks.org/resources. they want apply same theme like Resource Page.

**Comment by bensinjin** [comment]
@limage thx, I've enabled the taxonomy view for this - making these views now, is that sufficient for you to style? See http://dev.amani-zen-theme.peacegeeks.org/admin/structure/views/view/taxonomy_term/edit/page (this is the view) and will be used on all taxonomy pages. See http://dev.amani-zen-theme.peacegeeks.org/resource-type/pdf for example.

**Comment by limage** [comment]
@bensinjin Thanks Ben! I will start themeing today.

**Comment by limage** [comment]
@bensinjin https://github.com/PeaceGeeksSociety/amani/pull/1201
Please update dev site, the body content of each card may need truncated of characters count(200?), and image style(300px x auto) of thumbnail need adjust as well? thanks!

**Comment by bensinjin** [comment]
Thx @li I'll take a look some time today

**Comment by bensinjin** [comment]
Hey @li - so this image style you require - does it exist or need to be created?

**Comment by limage** [comment]
@bensinjin  It exist, need  to make it bigger, maybe 300px x auto?  previous one is 220x137px
http://dev.amani-zen-theme.peacegeeks.org/resource-type/pdf

**Comment by bensinjin** [comment]
This has been done and deployed.

**Comment by PeaceGeeksProjects** [comment]
Verified on Dev & LYM
