### ISSUE TITLE
Calendar << stops at January and >> stops at July

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/amani#1086]
http://dev.amani-zen-theme.peacegeeks.org/news-and-events
![1086](https://cloud.githubusercontent.com/assets/16202351/12825929/843a7c76-cb2d-11e5-8991-20c955d69af2.jpg)

**Comment by erica-scott** [comment]
Figured out this is not an issue of the calendar "stopping" but a stylistic thing when the month is 6 rows "long" which is why it happens to January and July. See image for clarification.
![screen shot 2016-02-25 at 11 54 19 am](https://cloud.githubusercontent.com/assets/5429661/13332393/9d79ca86-dbb6-11e5-8277-4a7217c60605.png)

**Comment by limage** [comment]
only set fixed height for Calendar block in front page of desktop version
https://github.com/PeaceGeeksSociety/amani/pull/1097
@bensinjin Please push to dev site, thanks!

**Comment by bensinjin** [comment]
Done.

**Comment by limage** [comment]
Lost  year & month(February 2016) in Calendar block

**Comment by bensinjin** [comment]
Should be resolved now

**Comment by PeaceGeeksProjects** [comment]
The month & year now appear OK.  HOWEVER, going forward skips a month except from Dec to Jan and Jul to Aug.  Going backward works fine...

**Comment by PeaceGeeksProjects** [comment]
Verified on Dev & LYM
