### ISSUE TITLE
New UI for resource feed grid 

### ISSUE THREAD

**Issue by isingh** [PeaceGeeksSociety/amani#1092]
Resource feed currently looks like this:
<img width="795" alt="screen shot 2016-02-16 at 1 35 33 pm" src="https://cloud.githubusercontent.com/assets/1025545/13091934/47ba8a64-d4b2-11e5-81ab-01cc01453f92.png">

This UI is inconsistent with other grids we have. Ideally we would like a consistent grid system, and also make the boxes similar. Ideally we need to work with a UI designer to get new mocks. Or we could use something like this:

<img width="894" alt="screen shot 2016-02-16 at 1 38 55 pm" src="https://cloud.githubusercontent.com/assets/1025545/13092013/ac2073b0-d4b2-11e5-9ae4-901afae749b9.png">

**Comment by erica-scott** [comment]
The merge request related to this issue does not fully resolve the issue, but will help make the section look more uniform until a new UI is provided by a designer.

**Comment by PeaceGeeksProjects** [comment]
Could we just use the current design but expand the boxes to be same height as the middle one in the top row?

**Comment by erica-scott** [comment]
After discussion with Renee and Magdi, decided to remove the "type" , "description" and "location" elements so that the blocks can be shortened. Still adding slight code to css because some titles wrap across two lines, but blocks are smaller now, and uniform. Was discussed that if this is an issue in the future, could look into a UI designer, but that this did not seem critical enough for that at this point.

**Comment by dannyzoujx** [comment]
Verified on dev, all the blocks have the same size and is correctly aligned

**Comment by MagdiRizkallah** [comment]
Confirmed
