### ISSUE TITLE
Front page boxes are misaligned

### ISSUE THREAD

**Issue by isingh** [PeaceGeeksSociety/amani#1143]
The boxes should be aligned correctly. This happens when images are different sized, or the captions.

<img width="631" alt="screen shot 2016-03-31 at 7 02 59 pm" src="https://cloud.githubusercontent.com/assets/1025545/14195864/47706edc-f773-11e5-9e91-dd4daab95c88.png">

**Comment by erica-scott** [comment]
Based on my initial testing, uploading a 'larger' image won't matter, because it ends up being cropped to the correct size anyways, so that won't cause the problem. So the issue is caused primarily by the title being longer. A simple fix would be to not let the title wrap, which I have completed for now. If this is not an acceptable fix we will probably need a front end person to look at this.

**Comment by PeaceGeeksProjects** [comment]
That will not work since the long title will overwrite the next  box title
![zen1143](https://cloud.githubusercontent.com/assets/16202351/14223377/8d966dce-f833-11e5-8d69-a781375606af.JPG)

**Comment by limage** [comment]
Fixed

**Comment by PeaceGeeksProjects** [comment]
Verified on Dev
