### ISSUE TITLE
Footer shows menu items disabled from main menu

### ISSUE THREAD

**Issue by isingh** [PeaceGeeksSociety/amani#1146]
The items that have been disabled in the main menu still show up in the footer. We should either automatically disable them, or allow us to configure the footer menu.

<img width="341" alt="screen shot 2016-03-31 at 7 07 58 pm" src="https://cloud.githubusercontent.com/assets/1025545/14195910/e86f1252-f773-11e5-9cd8-01b21088f49b.png">

The programs and resources are disabled for example.
<img width="110" alt="screen shot 2016-03-31 at 7 07 44 pm" src="https://cloud.githubusercontent.com/assets/1025545/14195911/e86f5a96-f773-11e5-8c33-dd5d34930305.png">

**Comment by erica-scott** [comment]
There are two different menus for the header/footer because we wanted to be able to show things in the footer that we don't show in header and vice versa, so if you want something enabled/disabled from the header edit them here http://dev.amani-zen-theme.peacegeeks.org/admin/structure/menu/manage/menu-amani-main-menu and if you want to enable/disable something from the footer edit it here http://dev.amani-zen-theme.peacegeeks.org/admin/structure/menu/manage/menu-configure-footer-links

**Comment by isingh** [comment]
Is that accessible from the amani admin?

**Comment by PeaceGeeksProjects** [comment]
Thanks Erica,  Could you please add a button with the edit footer menu links here with a brief explanation?
![zen1146](https://cloud.githubusercontent.com/assets/16202351/14222643/d4a2f81a-f827-11e5-873d-b1a73eab2d9d.JPG)

http://dev.amani-zen-theme.peacegeeks.org/admin/configure-amani

**Comment by bensinjin** [comment]
@PeaceGeeksProjects this ticket is no longer relevant to us. We now share the menu in header and footer. Moving to closed.
