### ISSUE TITLE
Calendar is displayed incorrectly when an event spans multiple days

### ISSUE THREAD

**Issue by isingh** [PeaceGeeksSociety/amani#1159]
To reproduce create an event that spans multiple days (you need start and end date, along with start and end times)

<img width="332" alt="screen shot 2016-04-06 at 6 34 15 pm" src="https://cloud.githubusercontent.com/assets/1025545/14337830/38c0ed3c-fc26-11e5-9496-28f20a28e292.png">

<img width="487" alt="screen shot 2016-04-06 at 6 02 14 pm" src="https://cloud.githubusercontent.com/assets/1025545/14337829/38c02d34-fc26-11e5-8e3b-9fd70ddcdb8c.png">

This is currently visible on dev site, and lym dev site.

**Comment by PeaceGeeksProjects** [comment]
There is a workaround for this issue for LYM GO Live.  I did it on Dev:
http://dev.amani-zen-theme.peacegeeks.org/
HOWEVER, it showed another limitation:  In the Month view, only the repeat days of the current Month show the event.  Could we then limit the days shown to current month OR show the event on relevant days of previous or next months?

We had to add a NOTE in the Amani Reference Manual (Amani Oldhad related limitations):
http://projectamani.org/content/addedit-event

Date - Date and Time when the event occurs.

    If it is a multi-day event, you may click ‘Show End Date’ to add the Date and Time when the event ends.

        NOTE: this will only show the event on the Detailed (week) view when you click on the first day link in the Calendar View.  **To see the event  in the Week View when you click on the any day link in the Calendar View, please use the Repeat Daily setup.**
    If it is an event that repeats on a regular basis (i.e. daily, weekly, monthly) you may select ‘Repeat’ at the bottom to set up a regular posting.

**Comment by bensinjin** [comment]
@PeaceGeeksProjects this is the last issue in the in progress queue. Can I get a status update on this?

**Comment by limage** [comment]
2. In the day view (http://dev.amani-zen-theme.peacegeeks.org/calendar-of-events/day/2016-04-03), it shows all the repeats every day. Could we just show the Start & End times. 
I'm still  working on this one

**Comment by PeaceGeeksProjects** [comment]
Hi Li - that is fine - thanks!




*Renee Black*,
*Executive Director*
#210 - 128 West Hastings Street
Vancouver, BC, V6B 1G8
*p.* 778-235-7458 | *e.* renee@peacegeeks.org
*skype**.* reneeontheroad
*pgp. *9253 3C6E 70B4 5211 6854 ED5E B585 C32D 264C 9CB6

**Comment by limage** [comment]
@bensinjin Please update the dev site from Amani-Zen-Theme branch, thanks!
https://github.com/PeaceGeeksSociety/amani/pull/1198

**Comment by bensinjin** [comment]
@limage Updated, should we move this do done so it can be checked?

**Comment by brandonq-appnovation** [comment]
@PeaceGeeksProjects 
Does your comment refer to an Event that spans multiple days (ie. the End date is days after the Start date), or an Event that repeats on multiple days (ie. there are repeats)?

For Events that span multiple days, the Events appear as you say in your comment. However, for 2, the ending of the Event displays at the top of the Calendar instead of at its given end time.
![screen shot 2016-05-11 at 7 55 18 pm](https://cloud.githubusercontent.com/assets/19274675/15202801/603c9e0e-17b2-11e6-8c89-a09d8ca94b92.png)


For Events that repeat on multiple days, 1 looks correct now. However, 2 and 3 appear to have issues:
2: The displayed Event shows what days of the week repeats, and only the start date, start time, and end time of the last day. On subsequent days after the first day, the Event appears at the top of the day instead of its scheduled start time (example shown: an Event that starts on May 27 and ends Jun 7, and goes from 06:00 to 18:15):
![screen shot 2016-05-11 at 7 44 48 pm](https://cloud.githubusercontent.com/assets/19274675/15202630/fc195e5e-17b0-11e6-84d4-152e44273c8d.png)

3: Both "Calendar of Events" and "Upcoming Events" shows multiple entries for the same repeating Event.
For "Calendar of Events", the first entry gives what days of the week it repeats, followed by a row of commas, then the last date with start and end times. All subsequent entries show the start date with start and end times in place of the days of the week it repeats.
![screen shot 2016-05-11 at 7 47 44 pm](https://cloud.githubusercontent.com/assets/19274675/15202733/daaf6f8c-17b1-11e6-86f1-9a622ef81ed1.png)

"Upcoming Events" displays like "Calendar of Events", except that all entries are like the subsequent entries, in that they show the start date instead of the days of the week it repeats.
![screen shot 2016-05-11 at 7 52 25 pm](https://cloud.githubusercontent.com/assets/19274675/15202741/eb174890-17b1-11e6-8a55-57122e4a99f9.png)

Can you clarify what needs to be done here?

**Comment by PeaceGeeksProjects** [comment]
@brandonq-appnovation Tx for your thorough testing
@PeaceGeeks @isingh @mackh @bensinjin Please review the doc at (https://drive.google.com/open?id=1bgrEghwSTS5XUe2OlCz57n-AhbsBdmUwBLOsSrItMu0) for my thoughts on how the Calendar views should look.  We can then assign the agreed upon views to a developer/themer to implement

**Comment by bensinjin** [comment]
@PeaceGeeksProjects all this seems overkill to me. Did we get specific requests to see events on a calendar daily/weekly/yearly also I have no idea how to get to the weekly/yearly displays - I don't see it listed anywhere immediately my initial reaction would be that it would never be seen unless we make it more visible somewhere.

Basically this is what I think we need:
1) People want to know when upcoming events are - the calendar block works fine for that I don't understand the need for 2 more blocks (upcoming events & calendar of events with a listing instead of a calendar display when your at http://dev.amani-zen-theme.peacegeeks.org/news-and-events)
2) People should be able to click a day, and see what events are in that day. In my opinion using yet another calendar for this actually makes it more difficult to peruse events on a given day. I would personally prefer just seeing something like this after clicking an event on the calendar:
![screen shot 2016-05-12 at 12 50 53 pm](https://cloud.githubusercontent.com/assets/3228323/15228272/36cce428-1840-11e6-964e-f25c79a9b61d.png)
... Just sort the events on a given day by the time they start, that seems the most natural.
3) Ditch the 24hour clock as per screenshot.

Maybe this is totally oversimplified but we're going to have a hard time bending that calendar to our will - I'm referring specifically to the daily/weekly/yearly displays and if you think about how much it's actually trying to do (in the most complex case: visually represent multiple events possibly on the same day starting at the same time spanning weeks and optionally repeating) - I think it's easier to just present this in words to the end user as apposed to them trying to figure out what this awkward calendar is trying to show them.

Anyways your thoughts are appreciated.

**Comment by PeaceGeeksProjects** [comment]
@bensinjin Your comments are appreciated.  A few comments to synch our thoughts .
1. Did we get specific requests to see events on a calendar daily/weekly/monthly/yearly:
 a. The Daily exists already, when you click on a Day of the Calendar
 b. The weekly view exist, but attainable only by knowing the url, so I'm not worried about it.
 c. What do you mean by Yearly view  ???
2. I don't understand the need for 2 more blocks (upcoming events & calendar of events)
 a. I agree with you, however, 'upcoming event' was in the design so we should:
    i. as a minimum, remove the calendar of events Block above it
   ii. seriously consider removing the 'upcoming event' block unless @PeaceGeeks  has objections
3. see what events are on that day: (Daily View)
 a. I fully agree with your idea pictured above.  A simple list will do quite well for me.

What do you think of my 'Calendar' View Changes in the Doc when events cross month boundaries?  Either solutions would give the correct impression on the overlapping days of previous and next month.

**Comment by bensinjin** [comment]
I'll take a closer look and see what's possible.

**Comment by bensinjin** [comment]
Ok so what I've done @PeaceGeeksProjects :
-At news-and-events path, at events on a particular day (http://dev.amani-zen-theme.peacegeeks.org/calendar-of-events/day/2016-05-09 for example) and on events nodes we see two blocks: Upcoming Events & Calendar.
-@limage the Upcoming Events block needs to be styled on events on a particular day (see above path) and event nodes to look like it does on the news-and-events page
-Events on a particular day are now just a list of items, we may need to style it a a bit?

**Comment by bensinjin** [comment]
@PeaceGeeksProjects I'm moving this to done, I've created a styling ticket for the remaining work that has been finished on this today (https://github.com/PeaceGeeksSociety/amani/issues/1200) this is the styling ticket I've assigned to @limage https://github.com/PeaceGeeksSociety/amani/issues/1202

**Comment by brandonq-appnovation** [comment]
I have verified that this has been done as @bensinjin has said:

- The homepage calendar of events displays as below, with bold and underlined links to indicate that an event occurs on that day.
![pgks_home_calendar](https://cloud.githubusercontent.com/assets/19274675/15263686/133a767e-1921-11e6-990f-17999deb04cc.png)

- The News and Events page has an Upcoming Events block and a Calendar of Events block. The first shows event names, dates, and times written out in text; the second shows a calendar like the one on the home page.
![rgks_news_and_events](https://cloud.githubusercontent.com/assets/19274675/15263749/94eebb3a-1921-11e6-9621-48ab02db43cc.png)

- The day view (for example, at http://dev.amani-zen-theme.peacegeeks.org/calendar-of-events/day/2016-05-16) shows a list of events ordered from earliest to latest start time. The same blocks from News and Events appear here, but require some theming. Parts of this page could still use some visual work, which can be addressed in #1202 
![pgks_calendar_day_view](https://cloud.githubusercontent.com/assets/19274675/15263725/5bc8bcf2-1921-11e6-8158-7c92a2320303.png)

- The event node page displays the event information, with the same blocks on the News and Events page, again requiring theming.
![pgks_event_node_page](https://cloud.githubusercontent.com/assets/19274675/15263779/e051879c-1921-11e6-96b7-a57aa6c27ad6.png)

@PeaceGeeksProjects Moving this to QA.

**Comment by PeaceGeeksProjects** [comment]
Verified on  Dev & LYM.
