### ISSUE TITLE
Style Blog nodes, Article nodes & blog landing page

### ISSUE THREAD

**Issue by bensinjin** [PeaceGeeksSociety/amani#1192]
An update on what I've done:
- A date field has been added to blogs, this is displayed on the node and at the view at /blog (previously the date at this view was showing the node created date)
- Two new fieldsets have been added: Tags & Type (on Articles display) Tags & Categories (on Blogs display) these can be used to style these taxonomy terms inline and will wrap both the fields.
-For both articles & blogs the node's display the same fields above the image: Date, Author, and the new fieldsets that encapsulate the taxonomy terms.

Please review these changes and style the necessary displays at /blog and article/blog nodes. I think we envision the terms in these new fields sets displaying inline and not differentiating (at least not visibly) the fact that these are two separate fields, just a comma separated list of links floated to the right. For author and date fields these should probably appear on the left something like <date>, <author>. Please confirm this with whoever is doing designs on this.

**Comment by bensinjin** [comment]
Please see https://github.com/PeaceGeeksSociety/amani/issues/1192. This has been deployed.

**Comment by PeaceGeeksProjects** [comment]
@PeaceGeeks @isingh What do you think of this as how these fields should appear?
The Tags (comma separated on a single line,) & Type/Category would be left justified.
![zen1192](https://cloud.githubusercontent.com/assets/16202351/15061692/0f97a3e6-12ed-11e6-8ec1-bdf80f62da29.JPG)

**Comment by isingh** [comment]
What is Essay and Article Type1?

**Comment by PeaceGeeksProjects** [comment]
There is no such thing as Essay type. Where are you seeing this?




*Renee Black*,
*Executive Director*
#210 - 128 West Hastings Street
Vancouver, BC, V6B 1G8
*p.* 778-235-7458 | *e.* renee@peacegeeks.org
*skype**.* reneeontheroad
*pgp. *9253 3C6E 70B4 5211 6854 ED5E B585 C32D 264C 9CB6

**Comment by isingh** [comment]
Its in the screenshot?

**Comment by PeaceGeeksProjects** [comment]
There are 3 'filtering' fields:
Author, Tags, Article Type / Blog Category.

the two you mention are tags & Article Type

**Comment by isingh** [comment]
I would love to have the keywords appear at the bottom. Right now they appear like this:

<img width="306" alt="screen shot 2016-05-06 at 9 23 45 am" src="https://cloud.githubusercontent.com/assets/1025545/15079249/4807ff80-136c-11e6-9840-674020dae83e.png">

It would be nice if they had a `Keywords: ` before them, just like you added `By: `. 

Also I am not sure if we need filtering information at the very top with Title. What do you think @PeaceGeeksProjects

**Comment by PeaceGeeksProjects** [comment]
Please do ALL styling comments on #1192.  there is my suggestion, propose other and let's get a desiogner opinion as well.

**Comment by PeaceGeeksProjects** [comment]
@isingh This is simply a suggestion.  We probably need a designer input on that...  You can modify the pic and present a design that Li can code against when we finalize our choice.

**Comment by isingh** [comment]
I am just curious from a user standpoint. If you navigate to an article, would you want to see the content first or keywords? Also in its current avatar, its hard to tell what is what. Like I got confused what is Essay and Article Type?

**Comment by PeaceGeeksProjects** [comment]
@isingh I agree with you on 'labeling' the filtering fields at the left.  I was just too lazy...

**Comment by isingh** [comment]
@PeaceGeeksProjects do you have a mockup of the node view? Right now on LYM I dont see author/date in node view. 
<img width="754" alt="screen shot 2016-05-06 at 9 35 34 am" src="https://cloud.githubusercontent.com/assets/1025545/15079534/e89b615c-136d-11e6-9aa6-23d80529e88d.png">

**Comment by PeaceGeeksProjects** [comment]
All views design is here https://projects.invisionapp.com/share/TR4QUJ3UY#/screens/116353463

The 'filtering' fields were added post design though.  This is why we still need a designer input for the final styling of these nodes.

**Comment by PeaceGeeksProjects** [comment]
@limage Please move the Tags below the description and if possible, put them on a 'labelled' single line separated by commas (e.g. Tags: tag1, tag2, tag3)

Moving back to in progress...

**Comment by limage** [comment]
Move tags below the description for all Blog, News, Event Node pages, and css tweaked!
@bensinjin Please update Dev site from Amani-Zen-Theme branch, and feature revert as well, thanks!

**Comment by bensinjin** [comment]
Pulled and reverted.

**Comment by brandonq-appnovation** [comment]
Most of this has been verified, but there is still some outstanding front end work. I also have a suggestion about how the new field names should display on the site.

Suggestion:
- Currently, the "Categories" field on Blog pages displays as "Categories" on the node page. However, in this field, only one Category can be chosen. Because of this, perhaps it should display as "Category" on the node page. Thoughts?

What needs work:
- Article pages and Blog pages do not look consistent with one another:
---> The content in Blog pages is aligned slightly farther to the left compared to Article pages
---> The Date and Author use different fonts. Blog pages use "Open Sans Condensed". Article pages use "Source Sans Pro" (which is the same font as the content for both kinds of pages).

What has been verified:
- "Date" field added to blogs
- Information from the "Date" field is visible both on the "/blogs" view and on blog node page
- Articles have two new fields: "Article Type" and "Tags"
- Blogs have two new fields: "Categories" and "Tags"
- The new fields display at the bottom of their nodes

Reassigning to Li to make edits to the front end.

**Comment by limage** [comment]
Categories could be multiple select, the label stay with "Categories", other fixed! https://github.com/PeaceGeeksSociety/amani/pull/1199

**Comment by brandonq-appnovation** [comment]
@limage , just a few more minor changes required and it'll be all good:
- On Article node pages, please change the font for the Article Author to Open Sans Condensed
- On Blog node pages, please change the formatting of the Categories so that they are not in all caps (style should be the same as the Tags below it)
- The “by” next to the Author Name on the the blog landing page, blog node page, and article node page is part of the article link right now. If possible, please make it separate from the link, and style it in the same way as the date to its left.
![pgks_change_by](https://cloud.githubusercontent.com/assets/19274675/15255462/fe647b8a-18f0-11e6-869d-1e4b1e836703.png)

**Comment by limage** [comment]
Done!
@bensinjin Please update dev site from Amani-Zen-Theme branch, thanks!
https://github.com/PeaceGeeksSociety/amani/pull/1206

**Comment by bensinjin** [comment]
deployed, moving to done.

**Comment by PeaceGeeksProjects** [comment]
Verified on Dev & LYM
