### ISSUE TITLE
Search bar doesnt show in footer in LYM

### ISSUE THREAD

**Issue by isingh** [PeaceGeeksSociety/amani#1210]
There is a search bar in Amani Dev footer.

**Comment by PeaceGeeksProjects** [comment]
@isingh That may be due to me Trying to satisfy your #1204 needs.  I had set the block to Footer instead of None here http://dev.amani-zen-theme.peacegeeks.org/admin/structure/block/manage/search/form/configure
Notice that would show it 'also' in the footer but only if you are logged in.  I reset it to None as it was.

Closing this issue
