### ISSUE TITLE
Calendar Day View disappeared

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/amani#1222]
![zen1222](https://cloud.githubusercontent.com/assets/16202351/15322778/992c4d32-1bf3-11e6-9c0b-316ce262a8d9.JPG)
FYI, I disabled the 'Calendar' View as Superadmin and re-enabled it. see #1204.  Now cannot get to the 'Day' view when I click on a day in the calendar.

**Comment by gurinderappno** [comment]
Issue is not reproducible since `Calendar Day View` actually does work.

Proof:
![screen shot 2016-05-17 at 4 07 14 pm](https://cloud.githubusercontent.com/assets/19229265/15342379/a299ec98-1c49-11e6-8bde-46db833f7957.png)

Is is possible that this is a url path problem and reporter's path wasn't configured properly in their `.htaccess` file.

**Comment by PeaceGeeksProjects** [comment]
@gurinderappno I tried on 3 different browsers and anonymous, AmaniAdmin, & SuperAdmin and finally on my iPhone, I still get Page Not found Error.

You obviously are NOT testing on our Dev instance, where all testing should be done...  Try this link:
http://dev.amani-zen-theme.peacegeeks.org/calendar-of-events/day/2016-05-17

**Comment by isingh** [comment]
An example:
<img width="1096" alt="screen shot 2016-05-17 at 4 49 37 pm" src="https://cloud.githubusercontent.com/assets/1025545/15343152/667aa81e-1c4f-11e6-84ce-24a5d505d879.png">

You will notice the date does actually have an event on it, but nothing is displayed.

**Comment by gurinderappno** [comment]
Looks fine to me: http://dev.amani-zen-theme.peacegeeks.org/calendar-of-events/day/2016-05-17

All I did was change the url `calendar-of-events/day/2016-05-17` to `acalendar-of-events/day/2016-05-17`, just added the `a` character and then reverted back to what it was previously, without the `a`. It may be a caching issue or something.

**Comment by PeaceGeeksProjects** [comment]
Thanks @gurinderappno It works fine now for me too (no clearing caching).  What made you think of adding the a character.  Does it have a special meaning?

I'll close the issue when you answer.  I can also try to reproduce it if it helps diagnose the exact issue.

**Comment by gurinderappno** [comment]
I just thought it was some problem specific to the dev server, since on my local the page worked fine. So I randomly thought to mess around with url as it would update the database entires for the view urls, and when changing the url no longer showed `Page not found`, I changed it back to the original ones which also started working.

**Comment by PeaceGeeksProjects** [comment]
Verified
