### ISSUE TITLE
Theme Article / News node page according to mock

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/amani#959]
https://projects.invisionapp.com/d/main#/console/4971962/109309163/comments

**Comment by HwaHueySoh** [comment]
https://projects.invisionapp.com/d/main#/console/4971962/116352528/preview

**Comment by PeaceGeeks** [comment]
@limage  - please compare with this - https://app.frontify.com/d/kGdWxDMw21JF/amani-zen-style-guide

**Comment by PeaceGeeks** [comment]
pink lines should not show on top
sidebar missing
comments should themed according to mock n sidebar
login/ register missing

**Comment by bensinjin** [comment]
@PeaceGeeksProjects can you point me to how this should look? The links appear to be broken

**Comment by PeaceGeeksProjects** [comment]
https://projects.invisionapp.com/share/KB4R6KBD9#/screens/116352528

**Comment by bensinjin** [comment]
What's the sidebar on the side? Other articles?

**Comment by MagdiRizkallah** [comment]
Yes!

**Comment by erica-scott** [comment]
This ticket has been completed based on these two fixes:
- Added 'Share' link 
- Minimized the black container for the title on the images for the sidebar articles

Also, two new tickets, related to this have been created, 1100 and 1101.

**Comment by dannyzoujx** [comment]
verified on dev. Share button is working, and the sidebar looks correct compare to the mock.

**Comment by MagdiRizkallah** [comment]
@erica-scott HOWEVER, the side bar is showing Programs not News
Moving backtoToDo

**Comment by erica-scott** [comment]
This was fixed by changing the view to display Articles instead of Programs. However, realized a couple other issues after making this fix. 
1) If an article does not have an image, the display is all messed up, and it looks very off. So I added a filter to the view to only show articles that have an image in the sidebar. If this is not an acceptable fix, we will probably need a themer to make some changes for a situation where an article does not have an image.
2) Some of the article titles are very long, and took up a huge amount of space on the image in the sidebar, so I added some code to shorten the title and add an ellipses so that it doesn't wrap, and meets the mock specifications. Again, if this is not a preferred fix, we could instead raise the black box on the image, depending on the title size, but this would mean some images would be covered a lot.

A pull request was made and merged. This code will need to be pushed to dev and the features will need to be reverted.

**Comment by PeaceGeeksProjects** [comment]
@erica-scott @isingh @PeaceGeeks 
1) I would rather not skip articles.  Please open an issue to fix the CSS
2) I am OK witj shortening the title ...

Also, the side bar still shows Programs...

Moving back to In Progress

**Comment by erica-scott** [comment]
No longer skipping articles. Created a new issue for the CSS issues.
https://github.com/PeaceGeeksSociety/amani/issues/1121

Will show articles instead of programs if the features are reverted.

**Comment by PeaceGeeksProjects** [comment]
We are discussing which articles should the sidebar show now that it is fixed.
Moving back to in progress

**Comment by erica-scott** [comment]
Decided to keep it simple. It displays the 3 most recent articles.

**Comment by PeaceGeeksProjects** [comment]
Verified on Dev
